### ISSUE TITLE
Bug when building HTML

### ISSUE THREAD

**Issue by titulebolide** [glpi-project/sphinx_glpi_theme#1]
Hi! 

I encountered and issue while building Sphinx with GLPI theme, when I follow the readme instructions.

Actually the issue comes from the fact that `spinx_glpi_theme.get_html_themes_path()` returns a list, thus `html_theme_path = [sphinx_glpi_theme.get_html_themes_path()]` is a nested list.

It is fixed if one uses instead:
```python3
html_theme_path = [*sphinx_glpi_theme.get_html_themes_path()]
#or
html_theme_path = sphinx_glpi_theme.get_html_themes_path()
```

Here is my log:
```bash
# Sphinx version: 3.0.1
# Python version: 3.7.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/titus/.local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/titus/.local/lib/python3.7/site-packages/sphinx/application.py", line 277, in __init__
    self._init_builder()
  File "/home/titus/.local/lib/python3.7/site-packages/sphinx/application.py", line 332, in _init_builder
    self.builder.init()
  File "/home/titus/.local/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 219, in init
    self.init_templates()
  File "/home/titus/.local/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 257, in init_templates
    theme_factory = HTMLThemeFactory(self.app)
  File "/home/titus/.local/lib/python3.7/site-packages/sphinx/theming.py", line 162, in __init__
    self.load_additional_themes(app.config.html_theme_path)
  File "/home/titus/.local/lib/python3.7/site-packages/sphinx/theming.py", line 173, in load_additional_themes
    abs_theme_path = path.abspath(path.join(self.app.confdir, theme_path))
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
```

Best!

**Comment by trasher** [comment]
Will fix, thank you
